### ISSUE TITLE
Adding additional python libraries to docker

### ISSUE THREAD

**Issue by grburgess** [fermiPy/fermipy#109]
I'm new to docker, so this may be the wrong place to ask this question, but is it possible to add additional python libraries to the docker? Namely, 3ML. Using a Mac (sorry), the ST distribution does not run so nicely, and the FermiPy docker is great (thanks!), but I mainly want to use it in combination with 3ML. 

cheers

**Comment by woodmd** [comment]
Yes this is easy to do.  However the approach will be slightly different depending on whether you want to run a tagged release or do actual code development.  In the former case I can just add 3ML as one of the pip dependencies in the dockerfile.  In the latter case you would need to first log into the docker container with a shell instance and install your development version of 3ML before launching the notebook server.  In this approach you would be using docker more as a VM than a containerized application so you would probably want to create a single persistent container rather than creating a new one for each session.  If this more along the lines of what you want let me know and I can provide more detailed instructions for running the container this way.

**Comment by grburgess** [comment]
@woodmd since I'm working on the development of 3ML, I would probably need to have more flexibility at the moment. Though, adding it onto the dependencies could help other users :). If it is not too much trouble, could you fill me in on the details for login in? Cheers!

**Comment by woodmd** [comment]
Sure.  Here's the basic sequence of commands.  First checkout your repo(s) into a working directory where you plan to run the container.  Start the container as follows:
```
docker run -it --name=3ml-container -v $PWD:/workdir fermipy/fermipy /bin/bash
```
The `name` flag is just to give you a handy way of remembering the name of the container later (otherwise it will autogenerate a name).  Then run the following from within the container session:
```
pip install <some extra packages>
cd <package directory>
python setup.py develop
/opt/conda/bin/jupyter notebook --notebook-dir=/workdir --ip='*' --port=8888 --no-browser
```
If you kill or otherwise exit your container session you can start it again at any point with the following:
```
docker start 3ml-container
docker attach 3ml-container
```
When restarting the container all of the packages you previously installed will still be there so you should only need to run the command to start jupyter notebook.  You can see a list of all the existing container instances with `docker ps -a`.

**Comment by grburgess** [comment]
Thanks! This worked perfectly.
