### ISSUE TITLE
PL and LP model in SED fitting 

### ISSUE THREAD

**Issue by suvenduat** [fermiPy/fermipy#126]
Hi,
How to fit a Power law (PL) and log parabola (LP) model to the SED using "gta.sed" function?
Thanks for the help.

**Comment by woodmd** [comment]
I'm not sure I fully understand your question but I think you're asking about refitting an SED to a different spectral parameterization than the one used for the global model.  There is functionality to do this in ```fermipy.castro``` but it presently isn't well documented.  If the source is sufficiently bright you could use a simple chi-squared fit to the flux points.  However for weaker sources this will breakdown since a Gaussian becomes a poor representation of the likelihood in each energy bin.

Another alternative would be to switch the parameterization of the source to a LP and rerun the ```sed``` method.  The [GTAnalysis.set_source_spectrum](http://fermipy.readthedocs.io/en/latest/fermipy.html#fermipy.gtanalysis.GTAnalysis.set_source_spectrum) method can be used to change the spectral parameterization of a source at runtime:
```
gta.set_source_spectrum('source_name', spectrum_type='LogParabola')
```
 You could also delete the source and add a new source with a LP parameterization at the same position.

**Comment by suvenduat** [comment]
I was asking exactly the same. Thanks for this suggestion. I was initially using a simple chi-squared fit to save time.

**Comment by suvenduat** [comment]
If I use gta.set_source_spectrum('source_name', spectrum_type='LogParabola'),
I get the following error:
189         fn = pyLike.SourceFactory_funcFactory().create(str(spectrum_type))
    190 
--> 191     for k, v in spectral_pars.items():
    192 
    193         v.setdefault('scale', 1.0)

AttributeError: 'NoneType' object has no attribute 'items'

The parameters list should take some default values but I am getting the above error.
