### ISSUE TITLE
Continuous integration tests for fermipy

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#13]
@woodmd - Do you have continuous integration tests for Fermipy set up?

If no, then we could try and use travis-ci.
They do have a feature to cache dependencies (e.g. the Science Tools and pip installs):
https://docs.travis-ci.com/user/caching/#Arbitrary-directories
But we might run into size limits for the VM.

At MPIK we also have a Jenkins running in an Ubuntu VM that we could use if travis-ci doesn't work.

**Comment by kialio** [comment]
Yea, we're working on this (I spent my spare time at the meeting last week figuring out if it was possible).

**Comment by woodmd** [comment]
Following Jeremy's lead I put together a basic setup with [travis-ci](https://travis-ci.org/fermiPy/fermipy) that seems to work.  Rather than figuring out how to install the fermipy dependencies into the ST python I'm installing anaconda python from scratch and using it in place of the ST python.  The tests that are there don't exercise that much of the ST functionality but it does at least demonstrate that you can import pyLikelihood and create a BinnedAnalysis instance.

At present the tests are using the precompiled ST binaries for ubuntu trusty that I'm downloading from the SLAC web server but I'm curious if you know of a better way of hosting large binary tarballs.  Maybe this would be a motivation for making a ST conda package.  I'm also surprised that the trusty ST build works on travis-ci even though the nodes are running precise.  Probably it would be better for us to create a dedicated build for precise.  We could also switch to using [trusty travis nodes](https://docs.travis-ci.com/user/trusty-ci-environment/) which I gather are still a beta feature.

**Comment by woodmd** [comment]
Since the travis-ci integration tests have been working smoothly so far I will go ahead and close this one.
