### ISSUE TITLE
flux-sensitivity does not match official performance results

### ISSUE THREAD

**Issue by deividribeiro** [fermiPy/fermipy#147]
Hello,
I have been working on reproducing the FermiLAT sensitivity results from the official performance page using the flux_sensitivity script, but was not successful. I emailed Jeremy Perkins, who tried a few things on his end to do the same thing. He made some improvements, but there were differences that would be better if discussed here. I'm pasting the email thread we had about this, starting with a link to his python notebook attempt at this. I'm also attaching my initial plot to compare with his (very similar!)

>Hi Deivid,
>
>I tried changing various parameters and am still not getting an exact match (you can see my efforts here: https://github.com/kialio/misc/blob/master/fermi/Sensitivity.ipynb).  I have asked for advice from some other folks and will get back to you.
>
>Jeremy
>
>On Tue, 20 Jun 2017 at 17:07 Jeremy S Perkins <jeremy.s.perkins@nasa.gov> wrote:
>Hi Deivid,
>
>One thing I just noticed (which might not be the final answer) is that the official curves take into account the loss of observing time due to SAA passages and the instrumental deadtime while fermiPy's default is to not do this. You'd need to make a livetime cube to do this but that's doable.  I'll do this on my end but it could take a bit.  If you've got a moment, go ahead and do that and let me know.
>
>Jeremy
>
>On Mon, 19 Jun 2017 at 12:32 Deivid Ribeiro <dr2792@columbia.edu> wrote:
>Hi Jeremy,
>
>Thanks so much for the quick response:
>
>System info:
>tehanu :: vetch/dribeiro/condor » uname -a
>Linux tehanu.nevis.columbia.edu 2.6.32-642.11.1.el6.x86_64 #1 SMP Tue Nov 15 14:13:21 CST 2016 x86_64 x86_64 x86_64 GNU/Linux
>
>Fermi Tools info:
>ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12-without-root
>
>Python:
>Server Information:
>
>You are using Jupyter notebook.
>
>The version of the notebook server is 4.3.1 and is running on:
>Python 2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 20 2016, 23:09:15)
>[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]
>
>Current Kernel Information:
>
>Python 2.7.13 |Anaconda 4.3.1 (64-bit)| (default, Dec 20 2016, 23:09:15)
>Type "copyright", "credits" or "license" for more information.
>>
>IPython 5.1.0 -- An enhanced Interactive Python.
>?         -> Introduction and overview of IPython's features.
>%quickref -> Quick reference.
>help      -> Python's own help system.
>object?   -> Details about 'object', use 'object??' for extra details.
>
>Command to run flux_sensitivity:
>
>dict = {'event_class': 'P8R2_SOURCE_V6',
> 'galdiff': '/a/data/tehanu/dribeiro/software/fermitools/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12-without-root/x86_64-unknown-linux-gnu-libc2.12/refdata/fermi/galdiffuse/gll_iem_v06.fits',
>  'glat': 0.0,
>   'glon': 0.0,
>    'index': 3.5,
>     'isodiff': '/a/data/tehanu/dribeiro/software/fermitools/ScienceTools-v10r0p5-fssc-20150518-x86_64-unknown-linux-gnu-libc2.12-without-root/x86_64-unknown-linux-gnu-libc2.12/refdata/fermi/galdiffuse/iso_P8R2_SOURCE_V6_v06.txt',
>      'min_counts': 10,
>       'nbin': 18,
>        'obs_time_yr': 10,
>         'output': 'LATsen3.500000.fits’}
>
>         from fermipy.scripts import flux_sensitivity
>         flux_sensitivity.run_flux_sensitivity(**dict)
>
>         Once I got results, I converted from MeV to erg to match the official result from the LAT Performance Page [https://www.slac.stanford.edu/exp/glast/groups/canda/lat_Performance.htm] ("differential_flux_sensitivity_p8r2_source_v6_all_10yr_zmax100_n10.0_e1.50_ts25_000_000.txt”):
>
>                meV2erg = 1.6021765300000047e-06
>                    tab = Table.read('/a/data/tehanu/dribeiro/FermiData/Sensitivities/LATsen3.500000.fits',hdu=1)
>                        sens = np.array(tab['e2dnde'])*meV2erg
>
>                        I can provide more information as needed.
>
>                        Thank you!
>
>                        Deivid Ribeiro
>                        Physics Graduate Student
>                        Columbia Astrophysics Lab
>                        dr2792@columbia.edu
>
>                        On Jun 19, 2017, at 12:05 PM, Jeremy S Perkins <jeremy.s.perkins@nasa.gov> wrote:
>
>                        Hello Deivid,
>
>                        Can you send me the commands you used to generate this plot with fermiPy?  Please be as detailed as possible.
>
>                        Thank you,
>
>                        Jeremy
>
>                        On Fri, 16 Jun 2017 at 16:00 Deivid Ribeiro <dr2792@columbia.edu> wrote:
>                        Dear Help Desk,
>
>                        I am working with Professor Brian Humensky in the VERITAS/CTA group at Columbia University. We are trying to update the CTA and Fermi sensitivity plot from Funk&Hinton 2013 (attached).
>
>                        I tried to reproduce the sensitivity plot for 10yrs, “P8R2_SOURCE_V6”, l=0,b=0, but am getting weird results as seen in my plots. It's not clear to me if there is an issue with the analysis tool I’m using (fermipy.flux_sensitivity). I was recommended this tool by Jeremy Perkins, who mentioned this is the tool that is used internally by the FermiLAT developers.
>
>                        My plots yield very similar results to the official pass8 sensitivity, but it does not match exactly and is even as far as 30% difference. However, it is reminiscent of results that are shifted by about 1/2 energy bin to the right. The values in the plot are for the various spectral indices from 1.5-3.5. Do you have any thoughts/insight for how to reproduce this plot? Should I expect results like these (worse sensitivity at low energies)?
>
>                        Thank you.
>
>                        Deivid Ribeiro
>                        Physics Graduate Student
>                        Columbia Astrophysics Lab
>                        dr2792@columbia.edu
>                        <attachment.png>
![attachment](https://user-images.githubusercontent.com/7332328/27655896-0292d004-5c15-11e7-9f8b-87e5c272962d.png)

**Comment by woodmd** [comment]
I think there are potentially two effects in play here:
1. The sensitivity calculation at the Galactic Center (l,b) = (0,0) is sensitive to how the IEM is interpolated since the diffuse intensity is strongly varying there.  For the sensitivity on the performance page we used a rather coarse map of the standard IEM so this may have resulted in some difference with respect to the fermipy tool which does not perform any rebinning of the IEM.  I suspect if you compared the sensitivity at higher latitude where the IEM is slowly varying you would see better agreement.
2. The official sensitivity was computed by doubling a 5 year exposure cube.  If you use a real exposure cube you will get small differences in sensitivity depending on the position on the sky.  For instance the official calculation did not consider the year of modified observations which increased the exposure toward the Galactic Center.

With that said I will do a quick check myself just to confirm that there isn't any issue with the calculation.

**Comment by woodmd** [comment]
I ran some tests that confirmed my initial suspicions.  The origin of the difference is due to inaccuracy in the IEM interpolation that was used for the official performance curves.  Attached are plots I generated comparing the official performance curve against the fermipy one at two sky positions: (l,b) = (0.0,0.0) and (l,b) = (0.0,30.0).  I generated the fermipy curve using a LT cube generated with zmax=100 and MET range 239557414 to 428903014 which I then rescaled to 10 years (using the `obs_time_yr` argument).  

At (l,b) = (0.0,30.0) the curves agree within ~2-4% while at the GC the official sensitivity is ~40-50% lower below 10 GeV.  However you can see that if I shift the position by 1 deg to (l,b) = (0.0,1.0) the fermipy sensitivity changes by more than a factor of 2 demonstrating that the sensitivity is rapidly varying on an angular scale < 1 deg which is comparable to the angular binning used for the official performance curves.  In summary the fermipy calculation gives the "correct" result at (l,b) = (0.0,0.0) but you should keep in mind that where the IEM is strongly varying the assumptions that go into this calculation begin to break down (e.g. it assumes that the IEM is not strongly varying over the PSF).

![official_vs_fermipy_0 0_0 0](https://user-images.githubusercontent.com/5733106/27665707-922ad028-5c23-11e7-952c-29a19e206eb0.png)
![official_vs_fermipy_0 0_30 0](https://user-images.githubusercontent.com/5733106/27665708-922c28e2-5c23-11e7-8a56-91b632a3092b.png)

**Comment by deividribeiro** [comment]
Thanks for these plots. I've been working on trying to reproduce them, but I have slightly different results. Its encouraging that these seem to be minor differences, but I'm curious why I am not even closer. Specifically, looking at the l=0,b=30, which were the best as your argument laid out well, I had some slightly worse results at the ~1GeV range:

![7751776f-ef42-41cd-a071-4b5ea6c7717f](https://user-images.githubusercontent.com/7332328/29045612-177e89a8-7b92-11e7-8940-ff2ff48da402.png)

Here's what I used for the LT cube:

Equatorial coordinates (degrees) = (240.634,-11.0124) (l=0,b=30)
Time range (MET) = (239557417,428903014)
Output from gtltcube: 239559507-428902174, about an hour off
Time range (Gregorian) = (2008-08-04 15:43:36,2014-08-05 03:43:31)
Energy range (MeV) = (100,300000)
Search radius (degrees) = 5
evclass = 128

galdiffuse/iso_P8R2_SOURCE_V6_v06.txt
galdiffuse/gll_iem_v06.fits
source spectral index: -2.0

**Comment by woodmd** [comment]
I can only guess that the remaining different may reflect some subtle difference in how you generated the LT cube.  For the official performance we apply zmax=100, no rocking angle cut, and set `roicut=no`.  Are you sure that you used the same settings?

**Comment by deividribeiro** [comment]
This must be it. I used

maketime['filter'] = 'DATA_QUAL>0 && LAT_CONFIG==1'
maketime['apply_filter'] = 'yes'
maketime['roicut'] = '**yes**'

and also 

expCube['dcostheta'] = 0.025
expCube['binsz'] = 1
expCube['phibins'] = 0
expCube['zmax'] = 100

I'll recompute and check the results. I'll also try the other directions (120,45 and 0,90) to confirm your hypothesis from earlier.

**Comment by deividribeiro** [comment]
I was able to reproduce your result exactly, but things were not as great for the other directions. I suppose these may be for similar reasons, since the differences are around 12-15%:

l=0,b=0, no roi_cut, 6yr LT (the first one you made):
![aec1dc94-37ed-4729-a3cf-b11968f5ff1e](https://user-images.githubusercontent.com/7332328/29095193-0e792daa-7c5e-11e7-948b-9275ce6283c6.png)

l=0,b=30, no roi_cut, 6yr LT (reproduction of yours):
![89dc0321-6268-4311-9db6-121e4fe94f51](https://user-images.githubusercontent.com/7332328/29095199-147ce1c4-7c5e-11e7-8ddc-d191beea9ac5.png)

l=0,b=90, no roi_cut, 6yr LT:
![c05630e7-40f3-4928-bef3-623742a74cba](https://user-images.githubusercontent.com/7332328/29095219-238df2a2-7c5e-11e7-8780-c0c48abd4699.png)

l=120,b=45, no roi_cut, 6yr LT:
![0df15640-31d3-414c-b064-2eba12b02fe0](https://user-images.githubusercontent.com/7332328/29095228-2ab5fbb0-7c5e-11e7-8031-b6eaf2daa125.png)

**Comment by woodmd** [comment]
I'm going to consider this resolved.  I suspect the remaining differences can be attributed to some combination of interpolation artifacts and differences between the LT cubes used for the calculation.
