### ISSUE TITLE
SED for mapcube templates

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/fermipy#208]
I have found an issue in the sed function when it calculates the SED points for sources modeled with map cube templates. This issue is generated by self.like[name].spectrum() in sed.py script for which the SED parameters are the renormalization and change of slope with respect to the map cube. 
For example the SED parameters for the IEM is:
In [18]: gta.like['galdiff']
Out[18]: 
galdiff
   Spectrum: PowerLaw
32     Prefactor:  3.220e+00  1.334e+00  1.000e-01  1.000e+01 ( 1.000e+00)
33         Index:  2.654e-01  1.079e-01 -1.000e+00  1.000e+00 (-1.000e+00)
34         Scale:  1.000e+03  0.000e+00  1.000e+03  1.000e+03 ( 1.000e+00) fixed
Since the pre-factor and index are completely wrong also the dN/dE is wrong.
A possible solution is to calculate the SED points from the flux or enflux.

**Comment by woodmd** [comment]
I never really anticipated that the `sed` would be used for mapcube sources.  The difficulty here is that the units of the model are carried in the mapcube file itself as opposed to in the spectral model object.  All ST flux methods return the flux of the spectral model only (i.e. the function by which we multiply the spatial component).  For point and extended sources this is fine because the spatial part is completely separable but for diffuse sources the spectral and spatial parts depend on one another.  I'd have to revisit the ST API for diffuse sources more carefully to understand if there's a way to pull out the flux somehow.  I'm pretty sure we could figure how to do this but it would require some changes to the way we handle diffuse sources in fermipy and potentially also in the STs.  A quick and dirty solution would be just to open the mapcube file ourselves (i.e. in fermipy), compute the spectral prefactors by integrating over the mapcube, and then carry around those prefactors in the source model object.

**Comment by dimauromattia** [comment]
A way to avoid this error is to consider the flux for each energy bin and calculate the energy spectrum assuming a value for the spectral index.
