### ISSUE TITLE
Fermipy docs CSS issue on RTD

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#21]
@woodmd - I noticed there's some issue with the docs on RTD:
http://fermipy.readthedocs.org/en/latest/

It looks like some CSS file is missing, see screenshot:
<img width="502" alt="screen shot 2016-03-27 at 18 13 44" src="https://cloud.githubusercontent.com/assets/852409/14069009/02b9c5aa-f448-11e5-99e6-51228d94f2e9.png">

Locally I see a few issues in the Sphinx build log, but I think they are unrelated:
https://gist.github.com/cdeil/a3c2be48129217d8d99e#file-gistfile1-txt-L15

Maybe the fix is to put this in your `docs/conf.py`:
http://read-the-docs.readthedocs.org/en/latest/theme.html#how-do-i-use-this-locally-and-on-read-the-docs
instead of just the line:
https://github.com/fermiPy/fermipy/blob/master/docs/conf.py#L162

But it depends on how you install stuff on RTD.

**Comment by woodmd** [comment]
Thanks for catching this.  What's odd is that the same setup was working fine as of a few weeks ago.  The issue seems to be the style sheet I added to enable line wraps in tables:

https://github.com/fermiPy/fermipy/blob/master/docs/conf.py#L195-L199

I've fixed it for now by commenting out this part of `docs/conf.py` but it would be nice to figure out how to get it working again.

**Comment by cdeil** [comment]
It's always a bit painful if an issue only occurs on RTD, where you can't ssh in and debug.
I don't know what the issue or fix is here, I haven't played with CSS for Sphinx docs much.

**Comment by woodmd** [comment]
Ok this is now fixed.  For the record I updated my `docs/conf.py` with the solution from snide/sphinx_rtd_theme#117.
