### ISSUE TITLE
residmap(): save "files" and "src_dict" dicts

### ISSUE THREAD

**Issue by terrijb** [fermiPy/fermipy#29]
I'd suggest recording the info in residmap() 's "files" and "src_dict" dicts to a standard file format (like yaml) so that they're easily findable (for multiple versions of residual maps). 
Since the files dict contains the paths to the fits files generated by residmap(), the information will be fully contained and would able to be reinstated without having to rerun residmap(). 

Fwiw, here's the snippet I'm using now:
maps=[]
maps = gta.residmap(...)
maps += gta.residmap(...)
with open('residmaps.yml', 'w') as outfile:
    outfile.write( yaml.dump(maps, default_flow_style=True) )

**Comment by woodmd** [comment]
I don't recommend using yaml for writing large data structures like maps -- numpy is much faster for this and also gives you a smaller file size.  In the 0.8.0 release I've implemented a `write_npy` option to `tsmap` and `residmap` that writes the output dictionary to a numpy file.  Note that since this saves the `Map` objects directly to the file you'll need to have fermipy installed to read back the files.  Here is the syntax to load the numpy file produced by `tsmap`:
```
gta.tsmap('myfit',write_npy=True)
o = np.load('myfit.npy').flat[0]
```
