### ISSUE TITLE
lightcurve TS

### ISSUE THREAD

**Issue by imereu** [fermiPy/fermipy#295]
I have tried to make a lightcurve with fermipy. The time interval is one month. In order, I do first setup and optimize on a certain source and then ask for the lightcurve point. The TS obtained after optimize is 131, instead the one related to the monthly point of the lightcurve is 170. Why this difference? I do not make cuts related to the sources that populate the ROI but the lightcurve automatically takes into account only the three sources in the ROI with greater TS (excluding all the others).

**Comment by dimauromattia** [comment]
Hi @imereu, you should consider that gta.optimize() works similarly to gta.fit() if there are no degeneracies between sources and their SED parameters. Is the TS=170 the one you get in only one time bin?

**Comment by imereu** [comment]
Only one time bin. 
Now I have write these options in lightcurve:
```
gta.free_source('galdiff')
gta.free_source('isodiff')
gta.fit()
lc = gta.lightcurve(src_name, nbins=1, free_background=True, free_sources=[src_name,'isodiff','galdiff'], max_free_sources=50, shape_ts_threshold=3, free_radius= 15.0)  
```

I work in a roi of 15 degree and the time interval (and lightcurve time bin) 1 month.
In this way I have the same condition (I think) for the fit and the lightcurve and I obtain a value of TS=117 after the fit and 123 associated at the lightcurve point.

**Comment by dimauromattia** [comment]
Hi @imereu, I am not surprised that you find a slightly different TS because the lightcurve is not doing exactly the same thing of the gta.fit(). In particular it is fixing some of the parameters of the ROI or some of the sources in order to make the fit in a shorter time bin more stable. You can check exactly the assumptions made by the fit in the light curve looking to the output in the folder that is generated by the analysis .

**Comment by imereu** [comment]
Thank you @dimauromattia!
