### ISSUE TITLE
TSMap does not work in GAL coordinates

### ISSUE THREAD

**Issue by jballet** [fermiPy/fermipy#297]
on v 0.17.4
We have declared CoordSys='GAL' in the binning entry of the configuration file.
The source maps are in GAL and the basic fit works fine.
However the TS map is completely false. The values do not correspond to those returned in the main fit, and the peak is not at the right place.
The reason appears to be that the TS map is computed in CEL, and therefore shifting the source maps does not work.
The same problem occurs in the mini TS map computed by the localization. Because of that the result of the Likelihood scan (which is done correctly) is incompatible with the TS map, and it fails because it is not centered at the right place.
A solution could be to perform the TS map in the same coordinate system defined by CoordSys, and (if in GAL) switch to CEL only for the Likelihood scan.

**Comment by dimauromattia** [comment]
Dear @jballet I have tried to make a simple analysis above 1 GeV of the source 4FGL J1637.7+4717 and everything seems to work. You can see in attachment the plot of the TS map found removing the source. The peak has reasonable values (sqrt(TS)=28) and the position is the correct one. I am using the newer Fermipy version but I can try to do the same test with 0.17.4.
<img width="687" alt="Screen Shot 2019-09-17 at 1 24 24 PM" src="https://user-images.githubusercontent.com/16928103/65064416-6c599f00-d94e-11e9-9ce2-2d0c16f9b380.png">

**Comment by jballet** [comment]
We have checked again and put our test files under ftp://ftp.cea.fr/incoming/y2k01/testFermiPy_37.tar.gz (available until Sept 27). The problem persists with fermiPy 0.18.0.
The localization procedure is completely off. The problem goes away as soon as we switch to CEL coordinates.
We wondered whether this could be due to the rogue ccube.fits file that fermiPy insists on recreating every time. That one is in CEL (and a different projection, AIT instead of ARC). But an overlay with ds9 shows that the alignment with the original counts cube in the srcMap_1.fits file is all right.

**Comment by jballet** [comment]
We have checked again today on fermipy 0.19 and the localization problem is still there.
I have put the test harness at ftp://ftp.cea.fr/incoming/y2k01/jbbglast/testFermiPy_37.tar.gz (available until April 14).

**Comment by eacharles** [comment]
Ok.   I think that the problem is that you are setting the coordsys at the component level, but not at the global level, where it is still defaulting to "cel".   
In order to be able to co-add components there needs to be some global configuration for the binning.   It looks like there current code is not picking up the coordsys from the first component. 

I tried moving the shared parameters for the components to a top level yaml binning block and that seems to work fine.   See attached figure.

Changing this would require a fair bit of work.  I'd prefer if you just changed the configuration file.    My version looks like this:

binning:
  coordsys: GAL
  proj: ARC
components:
- binning:
    binsz: 0.1
    enumbins: 14
    roiwidth: 40.800000000000004
  data:
    ltcube: ltcube_july09_pass8.fits
  gtlike:
    bexpmap: binned_exposure.fits
    edisp: false
    irfs: P8R2_SOURCE_V6
    srcmap: srcMap_1.fits
    use_external_srcmap: true
  model:
    catalogs: srcmdl_00.xml
  selection:
    emax: 40000.00000000005
    emin: 100.0
    evtype: 3
    zmax: 105.0
fileio:
  outdir: .
selection:
  dec: 20.652200000335476
  ra: 100.9749999998201

Your version:

![lat0004_localize](https://user-images.githubusercontent.com/14844706/78692322-8d63ec00-78ae-11ea-84c1-c55ed4ec6cc7.png)

My version:

![lat0004_localize](https://user-images.githubusercontent.com/14844706/78691822-ee3ef480-78ad-11ea-97d7-912ca0311aac.png)

**Comment by jballet** [comment]
OK, thank you for the explanation.
Our configuration file is generated automatically from the existing files, so it does not naturally have a "global" section. But we can generate one.
