### ISSUE TITLE
Incorrect NewMinuit fit quality

### ISSUE THREAD

**Issue by limyansky** [fermiPy/fermipy#311]
Hello, 

I am getting an issue where NewMinuit reports a fit quality of 3, even when the fit fails. An excerpt from one of my log files: 

```
2019-07-05 16:34:27 INFO    GTAnalysis.fit(): Starting fit.
2019-07-05 16:36:51 DEBUG   GTAnalysis._fit_optimizer_iter(): Retry fit iter: 1 quality: 3 edm:   0.0099 loglike: 12704263.201
2019-07-05 16:38:52 DEBUG   GTAnalysis._fit_optimizer_iter(): Retry fit iter: 2 quality: 3 edm:   0.0025 loglike: 12704263.200
2019-07-05 16:40:55 DEBUG   GTAnalysis._fit_optimizer_iter(): Retry fit iter: 3 quality: 3 edm:   0.0025 loglike: 12704263.200
2019-07-05 16:40:56 DEBUG   GTAnalysis.fit(): Fit complete.
2019-07-05 16:40:56 ERROR   GTAnalysis.fit(): NewMinuit failed with status code 156 fit quality 3
```

Best, 
Brent

**Comment by eacharles** [comment]
Hi Brent, I'm going through old issues and came across this one.
I'm not sure what you are asking for exactly.   
It can be kinda hard to figure out what the minuit error messages mean, but I suspect what this is telling you is that minuit can get a good covariance matrix.  I think that is what fit quality flag of 3 means.   Also, looking at the code in new minuit 
https://github.com/fermi-lat/optimizers/blob/master/src/NewMinuit.cxx
I see that the status code of 156 corresponds to 
156 = 100 + 24 + 16 + 8
Which means that three flags have been set, those flags are:
HasAccurateCovar()
HasPosDefCovar()
HasMadePosDefCovar()

Genrally, when you can't get a good covariance it means that you have too many degeneracies in your model.   
In any case, I don't see this being an issue with fermipy, it is just reporting that it can't get a good fit with the setup you gave it.   Try again with less free parameters.

**Comment by eacharles** [comment]
Ok, from a discussion with Sara Buson:

No I mean where the fit decides whether to go with Minuit or NewMinuit. I vaguely remember there is a loop, and choosing NewMinuit eventually it assigns quality = 3 (i.e. the number 3).


.. got it, referring to this page :
https://fermipy.readthedocs.io/en/latest/_modules/fermipy/gtanalysis.html#GTAnalysis.fit

the function “ _fit_optimizer” will check the quality for Minuit but there seems to be no check for NewMinuit. Since quality is set to 3 at the top of the loop, it will carry on that value. My understanding ..  I reported this on Nov. 21 in the slack channel, if this is the case the immediate fix should be to put “nan” or similar, from my and Jean’s understanding NewMinuit itself does not return a quality flag.


And my reply:
Well, for the old minuit a fit quality of 3 or 4 means that the fit succeeded at least in part.   
The check in question is in _fit_optimizer_iter around line 2821.  

            if quality >= min_fit_quality and status == 0:
                break

So I think the reason that the fit is not terminating is that the status is != 0.  
That is b/c the bits marking the covariance matrix not being computed are set. 
We can re-open this issue.  But I’m not sure what the right behavior is.   
If you have an example of a fit that works in Minuit but is marked bad in NewMinuit 
I can figure out which parts of the status word we might want to ignore and set the 
fit quality flag accordingly.

**Comment by sarabuson** [comment]
Hi Eric,

I can’t provide a simple example case unfortunately. During the past year I started working on a relatively large set of objects and was using NewMinuit for the fits. It appeared evident that in many cases the likelihood fits were misbehaving (errors were not properly evaluated) although the quality was flagged 3. I noticed a similar issue when reviewing a paper, and it turned out that the authors did use NewMinuit (and quality flag was 3).

I switched to Minuit as I could not find any reference to the quality flag in the NewMinuit manual (there was also some discussion with Jean who run into this same problem). With the Minuit minimiser everything has worked as expected in my analysis, and I had no issues anymore. Since then I have been recommending the use of Minuit being straightforward to interpret.

Best,
Sara

**Comment by eacharles** [comment]
Ok.   I'm updated the way fermipy handles the new minuit code so that it treats bits being set about the covariance matrix (which can happen if you haven't requested the covariance matrix to be computed) as part of the result and not as a failure.

**Comment by eacharles** [comment]
Ok.  This will be in the next release of fermipy.
