### ISSUE TITLE
Galactic diffuse spectrum

### ISSUE THREAD

**Issue by VardanB19** [fermiPy/fermipy#335]
Hi,

How I can restore the spectrum of galactic diffuse emission with the true normalization and index which will be based on the best-fit parameters of standard analysis with powerlaw or ConstantValue models? 
In particular for this case:

Name           : galdiff
TS             : 8304.49
Npred          : 147618.89
SpatialModel   : MapCubeFunction
SpectrumType   : PowerLaw
Spectral Parameters
Prefactor      :     0.8622 +/-    0.02441
Index          :   -0.08418 +/-  -0.008608
Scale          :       1000 +/-        nan

Thanks in advance.

**Comment by eacharles** [comment]
You can force the Prefactor to 1.0 and the Index to 0.0 and then fix them.   E.g.,;
gta.set_parameter("galdiff", "Prefactor", 1.0)
gta.free_parameter("galdiff", "Prefactor", free=False) 
 
Note, however, having the galdiffuse be so small is generally a sign that something else is not right with the fit to your ROI.   At high latittudes you might see if the galdiff and isotropic are heavily anti-correlated.   Otherwise you might want to make a residual map of the ROI and see if some bright-ish sources are missing.

**Comment by VardanB19** [comment]
Thanks for the answer.
I am mostly interested in the derivation of the galdiff SED after the fitting, since the Flux scale as well as the index look weird.
I was thinking, maybe I need to re-normalize the normalization and index? 
Here is an example of galdiff spectrum after fitting with Prefactor=1 and Index =0 using the command galdiff_sed = gta.sed('galdiff') in fermipy.
[
![galdiff_sed](https://user-images.githubusercontent.com/59999470/78616648-14946e00-7875-11ea-9f12-528e3c5eed6b.png)
](url)

**Comment by eacharles** [comment]
Fitting the galactic diffuse emission is a very complicated issue.   If you are just looking at a single, relatively small ROI, then it is usually enough to simply free the index and normalization of either the galactic diffuse or isotropic emission.   But I don't have any other general advice.  Try things and see what works best.   
I'm going to go ahead and close this issue now.

**Comment by VardanB19** [comment]
Ok, thanks
