### ISSUE TITLE
GTAnalysis.fit() does nothing

### ISSUE THREAD

**Issue by jefemagril** [fermiPy/fermipy#40]
Hello,

It seems under certain circumstances calling GTAnalysis.fit() returns immediately with None. I'm not sure why this happens.

I copied my working directory onto the SLAC computers. To recreate this, navigate to:
/nfs/slac/work/jmagill/cenatest
and run testscript.py. The last line of the script will print the output from fit(), which for me comes up as None.

I am using fermipy 0.9.2+27.g2e64 (which I believe has latest commit being 2e64779b7e4e89dd449010831ff9665586a0361b)

**Comment by woodmd** [comment]
This was happening because fit() was immediately returning when there were no free parameters.  In the latest commit fit() now returns a dictionary even when the number of free parameters is zero.

**Comment by jefemagril** [comment]
Ok, but the number of free parameters is not zero. Using pdb, I can see that `self.like.logLike.getNumFreeParams()` returns zero, but when I inspect `self.like` (just type `self.like` while in pdb at that point in the execution), I can see many free parameters listed in the model.

**Comment by woodmd** [comment]
You're right... this was a bug related to syncing the free/fixed state of the model parameters in the ``optimize()`` method.  It should now be fixed in the latest commit.  

One word of warning... I noticed that you > 30 free parameters in your XML model.  In general I would advise against trying to fit more than ~10 parameters at a time especially if those parameters include both shapes and normalizations.  Fitting lots of parameters at once usually causes MINUIT to converge very slow (if at all).

**Comment by jefemagril** [comment]
Thank you. Yes it appears to be fixed now.
