### ISSUE TITLE
ModuleNotFoundError when importing GTAnalysis

### ISSUE THREAD

**Issue by sushmitaagarwal** [fermiPy/fermipy#414]
I have installed fermipy version 1.0.1 using 

 `$ conda create --name fermipy -c conda-forge -c fermi fermipy`

When I try to initialize the basic analysis by importing GTAnalysis I get an error:
```
 
from fermipy.gtanalysis import GTAnalysis
Traceback (most recent call last):
  File " <stdin> ", line 1, in <module>
ModuleNotFoundError: No module named 'fermipy'
```

My Python version is 3.8.8
Let me know if there is a possible fix.

**Comment by henrikef** [comment]
Did you also install the fermi tools into your new environment? Should be something like `conda install -c conda-forge -c fermi fermitools` (call this from within the environment, so after the `conda activate fermipy` step).

**Comment by sushmitaagarwal** [comment]
Thank you for pointing that out. I realized I was not doing that.

I have now installed fermi using 
`conda create -n fermi -c conda-forge -c fermi fermitools python=3`

Then I activate the Fermi environment using
`conda activate fermi`

 Now I install fermipy in the activated fermi environment using:
`conda create --name fermipy -c conda-forge -c fermi fermipy`

Now to start the analysis, I activate the fermipy using `conda activate fermipy`

I am getting this error:

> (fermipy) user@user:~$ python
Python 3.7.10 | packaged by conda-forge | (default, Feb 19 2021, 16:07:37) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from fermipy.gtanalysis import GTAnalysis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/user/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtanalysis.py", line 21, in <module>
    import fermipy.gtutils as gtutils
  File "/home/user/anaconda3/envs/fermipy/lib/python3.7/site-packages/fermipy/gtutils.py", line 6, in <module>
    import pyLikelihood as pyLike
ModuleNotFoundError: No module named 'pyLikelihood'

I have installed fermipy in the fermi environemnt as suggested by @basuparth in issue #348
How can I resolve this issue?

**Comment by basuparth** [comment]
Hi @sushmitaagarwal . From your previous comments, it seems that you have created an environment within another environment, namely fermipy within fermi. What this means is that when you activate fermipy you no longer have access to the fermitools. A rough analogy would be that of having a smaller island(fermipy) within a bigger island(fermi), but by the very definition of an island, the smaller island is still isolated from the main bigger island. This results in 'No module named pylikelihood', as of course, 'pylikelihood' is not there in fermipy, the environment to which you have restricted yourself. The following steps should resolve the issue. 
First, remove the fermipy environment you created within the fermi environment. 
Now instead of executing 
`conda create --name fermipy -c conda-forge -c fermi fermipy` (which creates and restricts fermipy to its own namesake environment, separated and secluded)
execute 
`conda install -c conda-forge fermipy` 

Once the installation is done go ahead with your analysis. This should work hopefully if I have not missed anything. Just remember to activate the fermi environment before starting your analysis.

**Comment by sushmitaagarwal** [comment]
Ahaa it worked! 
I was creating a fermipy environment inside fermi environemnt when infact I just have to install fermipy package inside fermi environment. 
Thank you for a clear explanation.
