### ISSUE TITLE
Version mismatch with matplotlib and astropy?

### ISSUE THREAD

**Issue by jballet** [fermiPy/fermipy#430]
I have encountered two problems, which look like a conflict between versions:

1. I cannot use the write_roi call
/dsm/manip/glast/anaconda3/envs/fermi-2.0.18-fermipy/lib/python3.7/site-packages/astropy/table/table.py in insert_row(self, index, vals, mask)
   3061         except Exception as err:
   3062             raise ValueError("Unable to insert row because of exception in column '{}':\n{}"
-> 3063                              .format(name, err))
   3064         else:
   3065             self._replace_cols(columns)
ValueError: Unable to insert row because of exception in column 'spatialModel_file':
string operation on non-string array

2. I cannot use the make_plots option
/dsm/manip/glast/anaconda3/envs/fermi-2.0.18-fermipy/lib/python3.7/site-packages/fermipy/plotting.py in load_ds9_cmap()
    144     }
    145
--> 146     plt.register_cmap(name='ds9_b', data=ds9_b)
    147     plt.cm.ds9_b = plt.cm.get_cmap('ds9_b')
    148     return plt.cm.ds9_b
TypeError: register_cmap() got an unexpected keyword argument 'data'

I am using fermipy 1.0.1, fermitools 2.0.18, astropy 4.3.1 and matplotlib 3.4.3.

**Comment by GLAMURA81** [comment]
Hi @jballet , @henrikef ,
I do not know whether the first issue has been solved, by now, but I used to experience a similar error when calling 'write_roi'. After exploring the stack trace, I found an issue in 'roi_model.py'. Specifically, the error arises because the function 'add_to_table(self, tab)' attempts to write a 'row' dictionary that contains some None values. These cannot be implicitly converted into empty strings and cause the work-flow to break.

Assuming that the None values are null fields, I solved the problem like this:

1. created a backup of 'roi_model.py'
2. opened 'roi_model.py' and scrolled to line 521: `row = [row_dict[k] for k in tab.columns]`
3. added the following code lines (tabbed to the same level as the instruction in line 521):

`

            for ki in range(len(row)):
            kivalue = row[ki]
            try:
                kivalue_iterator = iter(kivalue)
            except:
                if (kivalue == None):
                    if (ki == 26): kivalue = 0.
                    else: kivalue = ''
                row[ki] = kivalue
`

The above code walks through the 'row' objects and replaces every non-iterable None object with an empty string, except for the 26th field, which expects a numeric value. In this case, if it is None, it gets replaced with 0. After this correction, my system is able to run 'write_roi' again.
