### ISSUE TITLE
is normal obtain differents values of the same code?

### ISSUE THREAD

**Issue by LeandroMatheumatical** [fermiPy/fermipy#471]
## Data Analysis Question

Hello,  i'm working with indirect detection of dark matter and i did the tutorial:

[https://github.com/fermiPy/fermipy-extra/blob/master/notebooks/draco.ipynb](url), 

So, i ran careffuly the draco.ipynp and i obtained different results of **_e2dnde_ul95_**  obtained in the tutorial.  It's Normal? 

My values : 
[5.85111070e-07 7.43452523e-08 3.63884243e-07 1.68467244e-07
 2.73626663e-07 7.17401267e-08 9.09434447e-08 1.48950313e-07
 1.11807142e-07 1.42976245e-07 1.64185758e-07 5.55730125e-07
 2.76505583e-07 4.30902614e-07 4.98536506e-07 9.36623550e-07
 8.22021750e-07 1.09973365e-06 1.47283116e-06 1.97482603e-06
 2.64108070e-06 3.54661763e-06 4.74794210e-06 6.50503719e-06]

Tutorial values : 
[  5.85009789e-07   7.43750866e-08   3.64154055e-07   1.68506855e-07
   2.72872618e-07   7.17419344e-08   9.09435675e-08   1.48945675e-07
   1.11805553e-07   1.42974103e-07   1.64185337e-07   5.47221111e-07
   2.76504956e-07   4.30895563e-07   4.98535032e-07   9.36584377e-07
   8.22021450e-07   1.09973348e-06   1.47283084e-06   1.97482588e-06
   2.64108025e-06   3.54661577e-06   4.74794210e-06   6.50503707e-06]

Any help is much appreciated. Thanks!

.

**Comment by henrikef** [comment]
Hi @LeandroMatheumatical! Looks like the deviations are small, within a percent or so? I wouldn't worry about it too much. Could be due to some minor changes in the minimizer etc.

I wanted to point out though that these examples are very old and in some cases outdated. For example, we now have better reconstruction (`P8R3_V2` instead of `P8R2_V6`) and corresponding instrument response, plus new  models/templates for both IEM and extragalactic diffuse. (I am hoping to at some point find the time to update them, but just keep in mind for now that these don't follow the current best analysis practices).
