### ISSUE TITLE
Wierd results from lightcurve()

### ISSUE THREAD

**Issue by sindrsli** [fermiPy/fermipy#517]
Hi!

I am working with a joint likelihood analysis of the extended source 4FGL J1723.5-0501e using data from 2008-2022. 

After optimizing the ROI with new sources and good fits, I was trying the gta.lightcurve() function on the extended source. No matter how many time bins I use I get weird results. The fluxes and uncertainties in all bins are identical through all decimal numbers. Is this a known bug? See plot from the results below:

![Lightcurve](https://user-images.githubusercontent.com/99318280/211804415-cf968fca-b103-4892-a1b3-6fd220f91924.png)

The config file, ROI files and the lightcurve.fits file are in the attached zip file.
[lightcurve.zip](https://github.com/fermiPy/fermipy/files/10392150/lightcurve.zip)

I am working on a Lunux computer with the newest verisoins of fermipy and fermitools.

**Comment by henrikef** [comment]
@sindrsli Can you please provide the fermipy logfile, both the general one (in your working directory) and one log file for one of the time bins (in the directory for that time bin).

**Comment by sindrsli** [comment]
General logfile:
[fermipy_lc.log](https://github.com/fermiPy/fermipy/files/10433997/fermipy_lc.log)

One of the time bins:
[fermipy.log](https://github.com/fermiPy/fermipy/files/10433963/fermipy.log)

I see in the terminal that I get some of these warnings:

> The maximal number of iterations maxit (set to 20 by the program)
allowed for finding a smoothing spline with fp=s has been reached: s
too small.

> There is an approximation returned but the corresponding weighted sum
of squared residuals does not satisfy the condition abs(fp-s)/s < tol.
  warnings.warn(message)

**Comment by henrikef** [comment]
@sindrsli thank you for bringing this up. 

Here's what I think is happening: 
* In your configuration file, you define `tmin` and `tmax` for each component rather than as part of the global selection. 
* When fermipy runs the analysis for a given time bin, the global `tmin` and `tmax` are replaced by the edges of that time bin, but the component selections are not adjusted.
* The component selection overwrites the global selection: You effectively re-fit the ROI for the full exposure 14 times instead of fitting for each time bin.

How to fix it:
* On your end: **Please try moving `tmin` and `tmax` out of the component selection into a global selection block** (see below).
* On our end: We should consider either any time selections in the component definitions, or throw a warning in case someone tries to produce a lightcurve but has component-wise time selection set.

Suggested sample config:

```
components:
 - { selection: {evtype: 32}}
 - { selection: {evtype: 28}}

selection:
  emax: 1000000 
  emin: 1000 
  evclass: 128
  filter: DATA_QUAL==1 && LAT_CONFIG==1
  glat: 16.96 
  glon: 17.9 
  tmax: 685859961
  tmin: 239557417
  roicut: 'no'
  zmax: 100
  radius: 8

```

**Comment by sindrsli** [comment]
Problem solved! Thanks!
