### ISSUE TITLE
Separate method for tsmap plots?

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#52]
While working on #51 I got this error:
https://travis-ci.org/fermiPy/fermipy/jobs/146089013#L1453

I'll fix the DISPLAY variable on travis-ci now.

Independent of the test, my suggestion would be to split the plotting out into a separate method:
https://github.com/fermiPy/fermipy/blob/486ae1df98e8c0777592a1a8c337546bc28d8a1a/fermipy/tsmap.py#L661

``` python
if make_plots:
            plotter = plotting.AnalysisPlotter(self.config['plotting'],
                                               fileio=self.config['fileio'],
                                               logging=self.config['logging'])

            plotter.make_tsmap_plots(self, maps)
```

@woodmd - Just a suggestion, if you don't like it just close the issue.

**Comment by woodmd** [comment]
Do you mean move it into a function that the user would call separately:
```
maps = gta.tsmap()
gta.make_tsmap_plot(maps)
```
Or moving the plotting into a separate function called within `tsmap`:
```
if make_plots:
    self._make_tsmap_plots(maps)
```
I think I'd prefer the latter solution.

Right now the plotting code is a bit of a mess but cleaning it up has been a secondary priority since I figured most people will want to make their own plots.  Eventually I'd like to remove the dependency of the plotter class on `GTAnalysis` entirely so that it can be used without importing the STs.

**Comment by cdeil** [comment]
I was advocating
```python
maps = gta.tsmap()
gta.make_tsmap_plot(maps)
```
and generally to always put code that does plotting or I/O in separate methods.

But it's just a small preference, do whatever you like best.

**Comment by woodmd** [comment]
Closing this now.  We've since settled on a pattern of delegating plotting to methods of `AnalysisPlotter` which have a syntax similar to the one @cdeil suggested (accepting an output dict as argument).
