### ISSUE TITLE
Have delete_sources() return the number of sources deleted for the given condition(s)

### ISSUE THREAD

**Issue by terrijb** [fermiPy/fermipy#6]
... which will make iterating on low TS sources more straightforward!

I don't know how to add the feature and enhancement labels, sorry!

**Comment by woodmd** [comment]
New functionality that addresses this issue is now available in 2772f1c5ec59f36f6ddb02d3e71ee33cfdd41b28.  Rather than return just the number of sources, `delete_sources` returns a list of the deleted Source objects.  These objects can be passed back to `add_source` if you want to later readd a source you deleted.
