### ISSUE TITLE
Documentation issue for the `edisp_disable ` option in the config file example

### ISSUE THREAD

**Issue by QRemy** [fermiPy/fermipy#621]
**Describe the bug**
The config example given in the documentation https://fermipy.readthedocs.io/en/latest/config.html#configuration-file 
has the lines `edisp_disable : ['isodiff','galdiff']` and `  galdiff  : '$FERMI_DIFFUSE_DIR/gll_iem_v07.fits'`.
However the document describing the `gll_iem_v07` diffuse model specifies :
 “The final IEM can therefore be considered measured in true energies rather than observed energies. Analysis using it will need to apply energy dispersion correction for accurate results.” (see page 13 [here](https://fermi.gsfc.nasa.gov/ssc/data/analysis/software/aux/4fgl/Galactic_Diffuse_Emission_Model_for_the_4FGL_Catalog_Analysis.pdf) ).
So I would expect : `edisp_disable : ['isodiff']`

**Comment by MiltosMichailidis** [comment]
Hi,
Thank you for reaching out.

In principle, you are right. But there is a small detail that you are missing here.
Both ['isodiff'] and ['galdiff'] should be derived with energy dispersion correction switched on.
The recommendation says that you should disable the energy dispersion correction for the model components that have already been corrected for energy dispersion or were fit to the data without taking energy dispersion into account. 
For analysis using older diffuse models (gll_iem_v06.fits or older) the energy dispersion should be turned off for both the isotropic and  the diffuse model, as well as any point-like or extended sources for which the spectral parameters are fixed to the 3FGL (also applies to 2FGL and 1FGL) values, since this is already pre-computed.

BUT, for 4FGL, only the isotropic template has already been corrected for energy dispersion. 
For your reference, here are further details: https://fermi.gsfc.nasa.gov/ssc/data/analysis/documentation/Pass8_edisp_usage.html

In the quickstart guide page at fermipy: https://fermipy.readthedocs.io/en/latest/quickstart.html the documentation is outdated (i.e., it refers to the older 3FGL catalog). As such, the line edisp_disable : ['isodiff','galdiff'] is correct.
But in the configuration page at fermipy:  https://fermipy.readthedocs.io/en/latest/config.html we have updated the file to gll_iem_v07 (and 4FGL) but without erasing the ['galdiff']. Indeed, the line there should read edisp_disable : ['isodiff']

I hope this addresses your comment. We are updating it right now.

**Comment by QRemy** [comment]
Resolved by #624. Thanks
