### ISSUE TITLE
Simulating hundreds of sources

### ISSUE THREAD

**Issue by dimauromattia** [fermiPy/fermipy#67]
I need to simulate hundreds of sources with a given flux, photon index and position in Galaxy. Making this inside the Science Tools takes a lot of time. Mainly this is due to add_source and delete_source functions. These two functions take between a few seconds and a few tens of second making the simulation of hundreds of sources time consuming. 

Simulations of sources could be done outside the Science Tools where given a list of sources and for each source you provide flux, spectral parameters and position and a function can simulate the photons and add these to the data.

Thanks

Mattia

**Comment by cdeil** [comment]
@dimauromattia - This is also functionality we want in Gammapy, and we have a few small building blocks for this:
- [sample_powerlaw](http://docs.gammapy.org/en/latest/api/gammapy.utils.random.sample_powerlaw.html)
- Some functions to simulate random positions in the Milky Way (see [here](https://gammapy.readthedocs.io/en/latest/astro/population/index.html))
- Compute npred for 1-d spectra for given 1D IRFs and Poisson fluctuate that (see [here](http://docs.gammapy.org/en/latest/spectrum/simulation.html)).
- Some code to compute `npred` (lon, lat, energy) cubes for given IRFs. These could then be interpolated and sampled, but that's not implemented.

Can you be a little more specific what you have in mind here?
- Do you want to simulate photons before or after taking IRFs / exposure into account?
- Do you need simulated events or would binned npred data following by `np.poisson` be enough for your applications?
- Do you have a specific method in mind how to implement the sampling? Is it the same one or a fundamentally different one to the one used in the Fermi ST that you find is slow?

**Comment by woodmd** [comment]
Mattia can speak to how he planned to implement the source sampling.  

The simulation would be of measured photons taking the IRFs into account.  Our plan is to generate `npred` cubes and throw poisson random numbers with `np.poisson`.  The `simulate_source` and `simulate_roi` methods already do this but since they use the STs for the model map calculation they're probably too slow if you want to simulate more than a 100 sources.

To generate the model maps ourselves we were planning to start from the existing functionality in fermipy for generating source maps:

https://github.com/fermiPy/fermipy/blob/master/fermipy/srcmap_utils.py

This handles the evaluation and interpolation of the IRFs and generates a source map with the appropriate spatial binning for the analysis.  What's currently missing is code that handles the spectral weighting and energy convolution (i.e. converting the source map to an `npred` map).

**Comment by dimauromattia** [comment]
To be more specific I'm thinking to a function that is able to simulate hundreds of sources with the gamma-ray spectrum, flux and position in the sky that I want. This can be applied for example to a randomly distributed blazar population with power-law or Log-parabola spectrum but also to pulsar population with Power-law with exponential cutoff distributed in the bulge of our galaxy. 

I'm thinking for example that you could give to the function vectors for the SpectrumType, Flux, longitude and latitude (or ra and dec) where each element of the vector is a source.

**Comment by dimauromattia** [comment]
I am successfully using Fermipy to simulate hundreds of sources so for me this issue is closed.
