### ISSUE TITLE
How to get help for Fermipy?

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#70]
I got a private email asking for help with Fermipy that I'm not qualified to answer.

@woodmd - For now I'll just suggest they contact you privately.

Is this what you want? Or do you prefer Github issues for user support? Or is there a mailing list?

Maybe you could mention how to get help somewhere in the docs
http://fermipy.readthedocs.io/en/latest/index.html

If you want you can point people to the Gammapy mailing list
https://groups.google.com/forum/#!forum/gammapy
For some reason this isn't working so far though, no-one's using it, people prefer private email.

**Comment by woodmd** [comment]
There's no mailing list although there is a fermipy.developers@gmail.com address for the fermipy organization.  Currently this just forwards to my personal email but at some point we might redirect that to a larger group of developers and/or a dedicated mailing list.

Generally I would recommend people use github issues if they have questions since it creates a public record and also leaves the option for other users to provide feedback or suggestions.

**Comment by cdeil** [comment]
@woodmd - Could you add a sentence or paragraph somewhere (I'm not sure where) mentioning that Github issues should be used to get help?
(searching the docs for "help" currently comes up (almost) empty: http://fermipy.readthedocs.io/en/latest/search.html?q=help&check_keywords=yes&area=default )

**Comment by woodmd** [comment]
Ok I've added a sentence to the docs landing page.
