### ISSUE TITLE
Split up castro.py in multiple files?

### ISSUE THREAD

**Issue by cdeil** [fermiPy/fermipy#82]
@woodmd - How about splitting up https://github.com/fermiPy/fermipy/blob/master/fermipy/castro.py into multiple files.

I think this would make it clearer which class depends on which parts of Fermipy (and could possibly be used in Gammapy).

Also: maybe rename or explain the name "castro"?
What's a Castro?
It's cryptic for me.

It's to compute results in this format, right?
http://gamma-astro-data-formats.readthedocs.io/en/latest/results/binned_likelihoods/index.html

Context: https://github.com/gammapy/gammapy/issues/698

cc @joleroi

**Comment by woodmd** [comment]
I agree that it's about time we split up castro.py.  For the most part this code should have minimal dependencies on other parts of fermipy (or at least this is what we've tried to achieve).  You're correct that this code is intended for reading and manipulating binned likelihoods both for an individual target or a 2D grid of positions (the likelihood/TS cube).

The origin of the name is a bit obscure.  To make visualizations of the flux likelihood profiles vs. energy bin we often use a 2D image rendered with the "jet" colormap.  At some point Anna Franckowiak (who was a postdoc at SLAC at the time) observed the similarity to the rainbow flags in the SF castro district and started calling them castro plots and the name has stuck around informally since then.  I'm not particularly attached to the name so we could consider changing it when/if we migrate this to gammapy.
