### ISSUE TITLE
sedlnl plot alignment error bars and castro bands

### ISSUE THREAD

**Issue by ralphbird** [fermiPy/fermipy#89]
When producing an SED with bins that aren't of equal width across the range (e.g. a final bin which is wider to cover the "remaining" energy range) the error bars do not align with the castro bands.  It looks like the castro bands assume equal width bins (at least for plotting).

![3fgl_j1952 9 3253_sedlnl](https://cloud.githubusercontent.com/assets/8191067/19360344/0276eb8a-9133-11e6-97f7-b43fbd9200c8.png)

**Comment by woodmd** [comment]
This is now fixed in the master branch which you can install by following the [Building from Source](http://fermipy.readthedocs.io/en/latest/install.html#building-from-source) instructions.  Note that the `SEDPlotter` class now gives you more flexibility to tweak the SED plot to your liking:
```
from fermipy.plotting import SEDPlotter
import matplotlib.pyplot as plt
o = gta.sed('mysource')
p = SEDPlotter(o)
plt.figure()
p.plot(marker='x', showlnl=True, cmap='Blues', ul_ts_threshold=9, cmap_trunc_hi=0.5)
```
The `cmap_trunc_hi` option can be used to truncate the color scale at the given fraction of the color map range.  You can use this to improve the contrast between castro bands and the flux points if you find that the bands are too dark.
