### ISSUE TITLE
Error while loading xml file

### ISSUE THREAD

**Issue by skumarudel** [fermiPy/fermipy#90]
Hi, 
   When I try to load a model file I am getting this error

gta.load_xml('srcmdl_00.xml')
2016-10-13 16:37:31 INFO     GTAnalysis.load_xml(): Loading XML
2016-10-13 16:37:31 INFO     GTBinnedAnalysis.load_xml(): Loading /home/research/Pass8/Data20161010/srcmdl_00_00.xml
Fatal error at file "", line 0,column 0
 Message: An exception occurred! Type:RuntimeException, Message:The primary document entity could not be opened. Id= /home/research/Pass8/Data20161010/srcmdl_00_00.xml
---

RuntimeError                              Traceback (most recent call last)
<ipython-input-11-3bf89137083a> in <module>()
----> 1 gta.load_xml('srcmdl_00.xml')

/home/sajan/.local/lib/python2.7/site-packages/fermipy-0.9.1_19.g0676-py2.7.egg/fermipy/gtanalysis.pyc in load_xml(self, xmlfile)
   2541 
   2542         for c in self.components:
-> 2543             c.load_xml(xmlfile)
   2544 
   2545         for name in self.like.sourceNames():

/home/sajan/.local/lib/python2.7/site-packages/fermipy-0.9.1_19.g0676-py2.7.egg/fermipy/gtanalysis.pyc in load_xml(self, xmlfile)
   4369         xmlfile = self.get_model_path(xmlfile)
   4370         self.logger.info('Loading %s' % xmlfile)
-> 4371         self.like.logLike.reReadXml(str(xmlfile))
   4372         if not self.like.logLike.fixedModelUpdated():
   4373             self.like.logLike.buildFixedModelWts()

/opt/ScienceTools/v10r0p5/x86_64-unknown-linux-gnu-libc2.12/lib/python/pyLikelihood.pyc in reReadXml(_args)
   5621     def reReadXml(_args):
   5622         """reReadXml(self, string xmlFile)"""
-> 5623         return lib_pyLikelihood.SourceModel_reReadXml(_args)
   5624 
   5625     def writeXml(_args):

RuntimeError: SourceFactory::readXml:
Input xml file, /home/research/Pass8/Data20161010/srcmdl_00_00.xml , not parsed successfully.

Any help??
thanks!

**Comment by woodmd** [comment]
The `load_xml()` method should only be used to read models generated with `write_xml()`, e.g.
```
gta.write_xml('mymodel.xml')
# Do Some Fits
gta.fit()
# Restore model to previous state
gta.load_xml('mymodel.xml')
```
However some care should be taken when using `load_xml()`.  This method can only update spectral parameters of existing sources within the ROI.  If you've added or removed sources or changed their spectral model (e.g. from PowerLaw to LogParabola) then you should use `write_roi()` and `load_roi()`.  Generally I would recommend using these methods whenever you need to save/restore your analysis since they are guaranteed to always put the model into a consistent state.

In your specific example the following should work,
```
gta.load_xml('srcmdl.xml')
```
The reason it was failing is that the method automatically appends a unique suffix to the filename for each model component.

Only a completely separate note, I'd recommend upgrading to the latest fermipy release (0.11.0) as there have been a number of changes and improvements to the output file formats relative to the release you're current using (0.9.x).  There are instructions for upgrading fermipy on the installation page.
